---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: site/content/work
  label: Work
  create: all
  match: "**/*"
- type: directory
  path: site/content/people
  label: Employees
  create: all
  match: "**/*"
- type: directory
  path: site/content/pages
  label: All Pages
  create: all
  match: "**/*"
upload_dir: src/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.45.1
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.45.1
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.45.1
